[[redirects]]
    from = "/home"
    to = "https://shattereddisk.github.io/rickroll/rickroll.mp4"

[[redirects]]
  from = "https://bavins.lv/w"
  to = "https://raw.githubusercontent.com/villhelmms/windows/main/winutil.ps1"
  status = 301
  force = true
