baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Vilhelms Bavins'
theme = "new-theme"

[[menus.main]]
name = 'Sākums'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Aktivitātes'
pageRef = '/activities'
weight = 20

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Kontakti'
pageRef = '/contacts'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
